version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: mrohith29/foodprint-api:latest
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    image: mrohith29/foodprint-frontend:latest
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
